### ISSUE TITLE
Feature request: piped input

### ISSUE THREAD

**Issue by richardlehane** [tw4l/brunnhilde#1]
Hi Timothy,
great project! It'd be cool to have another mode of operation where brunnhilde reads a csv piped into STDIN. This would allow you to do something like:

```
sf -csv directory | python brunnhilde.py
```

Benefit would be that users could have more control over options passed to sf (like choice of hash, signature file, etc.). 

Re. type of reporting: have you seen Ross Spencer's DROID analysis projects https://github.com/exponential-decay/droid-sqlite-analysis ? May give you some ideas as to useful info to report.

cheers
Richard

**Comment by timothyryanwalsh** [comment]
Thanks, Richard! I agree, that could be very helpful - I'll look into building out that functionality in the next version.

And thanks also for pointing out Ross' project -- very cool and a great source of ideas.

Tim

**Comment by tw4l** [comment]
Hi @richardlehane , hope you're doing well!  I just released Brunnhilde 1.9.0, which includes a `--stdin` option that will read a Siegfried CSV from piped stdin (e.g. `sf -csv . | brunnhilde.py --stdin . /path/to/output/dir`), as well as a `--csv` option that will take a Siegfried CSV file on disk as input. More details are available in the project README and [release notes](https://github.com/tw4l/brunnhilde/releases/tag/v1.9.0). Better late than never? 😆

**Comment by richardlehane** [comment]
wow! Thanks Tessa and congrats on the release :)
