### ISSUE TITLE
add -partition option for unhfs

### ISSUE THREAD

**Issue by bdietz** [tw4l/brunnhilde#45]
Hey Tessa, would you be willing to consider adding the -partition option for unhfs so that a user could extract files from a specific partition, similar to the change you made to allow a user to specify the sector offset with tsk_recover? Currently, w/ the hfs option, brunnhilde only extracts files from the first partition. Thanks for considering it! --Brian

**Comment by tw4l** [comment]
Hi Brian! Sure, I'd be happy to add the -partion option for unhfs to Brunnhilde. I should be able to carve out a bit of time on Friday to take a look at this. Thanks for your patience!

**Comment by tw4l** [comment]
Hi @bdietz,  just a quick note to say that I just released Brunnhilde 1.9.0, with new `--hfs_partition` and `--hfs_fsroot` options for `unhfs`. More details are available here: https://github.com/tw4l/brunnhilde/releases/tag/v1.9.0. You should be able to update with `sudo pip install --upgrade brunnhilde`.

Thanks again for the suggestion, and for your patience! This release ended up being a bit bigger in scope than I had planned at first and was definitely delayed by COVID malaise, so it took me a bit longer than I anticipated. I hope you find the new features useful!
