### ISSUE TITLE
Add virus scan report to HTML?

### ISSUE THREAD

**Issue by kieranjol** [tw4l/brunnhilde#50]
Would there be any value in adding the virus scan report to the HTML? Just wondering if there was a design decision around that. I'm totally not a web dev but I could look into adding it? I know it would be useful for my use case - which is having the HTML as a lovely human readable report.

**Comment by tw4l** [comment]
Hi @kieranjol - as of Brunnhilde 1.9.0, the (newly restyled) HTML report does include a virus scan report section ([release notes here](https://github.com/tw4l/brunnhilde/releases)). It's written into the report if virus scanning is enabled on a supported platform, so currently not on Windows. But I'd be happy to see that gap addressed! I see your comment on that in #29 so I'll close this issue and let's keep talking there.
