### ISSUE TITLE
Installation Update

### ISSUE THREAD

**Issue by NiamhElizabeth** [tw4l/brunnhilde#56]
I've noticed that the installation notes may need to be updated with regard to Mac users.
In order to install, the instructions state to input the following:
sudo pip install brunnhilde
This did not work for me. I went back and forth a bit before trying:
sudo pip3 install brunnhilde
This worked and I was able to successfully install the software.

**Comment by kieranjol** [comment]
+1, this could be worth updating.

**Comment by tw4l** [comment]
README change merged - thank you @kieranjol !
